Repository noobgg-team/noobgg, pull requests merged in 2025-06, with the labels that each got.

#3 feat: created sample folder structure (Controllers, Routes)
  apps/api/src/controllers/any-route.controller.ts
  apps/api/src/controllers/main.controller.ts
  apps/api/src/index.ts
  apps/api/src/routes/any-route.ts
  apps/api/src/routes/index.ts
Labels: documentation, enhancement, good first issue

#8 Feature/add project readmes
  README.en.md
  README.md
  README.tr.md
Labels: documentation

#9 feat: add next-intl package and related dependencies
  apps/web/package.json
  bun.lock
Labels: enhancement

#11 Fix: Update git clone URLs in README files
  README.en.md
  README.tr.md
Labels: documentation

#14 Add Game and Distributor schemas
  apps/api/src/db/schema.ts
Labels: codex

#17 feat: implement CRUD operations for distributors and update routing
  apps/api/src/controllers/distributors.controller.ts
  apps/api/src/routes/distributors.ts
  apps/api/src/routes/index.ts
Labels: enhancement, good first issue

#27 Implement Platform CRUD API
  apps/api/src/controllers/platforms.controller.ts
  apps/api/src/lib/zod-schemas/platforms.ts
  apps/api/src/routes/index.ts
  apps/api/src/routes/platforms.ts
Labels: codex

#28 Add Platform CRUD UI
  apps/web/app/dashboard/platforms/[id]/edit/page.tsx
  apps/web/app/dashboard/platforms/new/page.tsx
  apps/web/app/dashboard/platforms/page.tsx
  apps/web/app/layout.tsx
  apps/web/components/platforms/platform-form.tsx
  apps/web/components/platforms/platform-table.tsx
  apps/web/components/query-provider.tsx
  apps/web/features/platforms/api/actions.ts
  apps/web/features/platforms/api/use-platforms.ts
  apps/web/package.json
  apps/web/types/platform.ts
  bun.lock
  packages/shared/index.ts
  packages/shared/schemas/platform.ts
Labels: codex

#32 feat: Add ufukozendev to contributors list
  README.en.md
  README.md
  README.tr.md
Labels: documentation

#40 Move README files to .github directory
  .github/README.en.md
  .github/README.md
  .github/README.tr.md
Labels: documentation

#42 feat: language support added to work without routing through middleware, language-switcher component created
  apps/web/app/page.tsx
  apps/web/components/language-switcher.tsx
  apps/web/i18n/request.ts
  apps/web/messages/en.json
  apps/web/messages/tr.json
  apps/web/middleware.ts
Labels: enhancement, frontend

#30 Add ESLint to API project
  apps/api/eslint.config.mjs
  apps/api/package.json
  apps/api/src/controllers/distributors.controller.test.ts
  bun.lock
Labels: codex

#59 Add event DB schemas
  apps/api/src/db/schemas/event-attendees.drizzle.ts
  apps/api/src/db/schemas/event-invitations.drizzle.ts
  apps/api/src/db/schemas/events.drizzle.ts
  apps/api/src/db/schemas/schema.ts
Labels: enhancement, good first issue, codex, backend, high-priority, infrastructure

#71 feat: added language and theme switcher to header component
  apps/web/app/layout.tsx
  apps/web/components/language-switcher.tsx
  apps/web/components/mvpblocks/header-1.tsx
  apps/web/components/theme-switcher.tsx
  apps/web/styles/globals.css
Labels: documentation, enhancement, help wanted, good first issue, frontend, high-priority

#74 Implement CRUD Operations for Event Invitations Management (Partially Completed)
  apps/api/src/controllers/event-invitations.controller.ts
  apps/api/src/routes/event-invitations.ts
  apps/api/src/routes/index.ts
  packages/shared/index.ts
  packages/shared/schemas/event-invitations.ts
Labels: enhancement, help wanted, good first issue, crud, backend, api, typescript

#94 Add swagger-ui-express and yamljs dependencies to package.json
  apps/api/openapi.yaml
  apps/api/src/index.ts
  apps/api/src/types/yamljs.d.ts
  apps/api/tsconfig.json
  bun.lock
  package.json
Labels: bug, documentation, enhancement, help wanted, good first issue, backend, high-priority, api, architecture

#96 Add 3D globe with React Three Fiber
  apps/web/components/ThreeFiberGlobe.tsx
  apps/web/components/mvpblocks/landing-hero-section.tsx
  apps/web/components/mvpblocks/sparkles-logo.tsx
  apps/web/package.json
Labels: documentation, enhancement, question, frontend, ui, high-priority, ui-components, next.js, typescript, web

#121 ✅ Add comprehensive tests for PlatformsController
  apps/api/src/controllers/platforms.controller.test.ts
  apps/api/src/controllers/user-profiles.controller.test.ts
Labels: backend

#131 3d world updated with real map
  apps/web/components/ThreeFiberGlobe.tsx
  apps/web/components/mvpblocks/landing-hero-section.tsx
  apps/web/package.json
  apps/web/public/data/all.geojson
Labels: frontend, ui, high-priority, ui-components, next.js, typescript, web

#133 feat: implement locale middleware for language detection and message …
  apps/api/src/index.ts
  apps/api/src/middleware/locale.ts
Labels: backend, architecture, next.js, typescript

#134 Refactor all controllers to use DTOs and centralized error handling
  apps/api/openapi.yaml
  apps/api/src/controllers/v1/distributors.controller.ts
  apps/api/src/controllers/v1/event-attendees.controller.ts
  apps/api/src/controllers/v1/event-invitations.controller.ts
  apps/api/src/controllers/v1/events.controller.ts
  apps/api/src/controllers/v1/game-ranks.controller.ts
  apps/api/src/controllers/v1/games.controller.ts
  apps/api/src/controllers/v1/languages.controller.ts
  apps/api/src/controllers/v1/platforms.controller.ts
  apps/api/src/controllers/v1/user-profiles.controller.ts
  apps/api/src/middleware/errorHandler.ts
  apps/api/src/utils/bigint-serializer.ts
  packages/shared/dto/distributor.dto.ts
  packages/shared/dto/event-attendee.dto.ts
  packages/shared/dto/event-invitation.dto.ts
  packages/shared/dto/event.dto.ts
  packages/shared/dto/game-distributor.dto.ts
  packages/shared/dto/game-mode.dto.ts
  packages/shared/dto/game-platform.dto.ts
  packages/shared/dto/game-rank.dto.ts
  packages/shared/dto/game-region.dto.ts
  packages/shared/dto/game.dto.ts
  packages/shared/dto/language.dto.ts
  packages/shared/dto/lobby-language.dto.ts
  packages/shared/dto/lobby-member.dto.ts
  packages/shared/dto/lobby.dto.ts
  packages/shared/dto/platform.dto.ts
  packages/shared/dto/user-profile.dto.ts
Labels: documentation, duplicate, enhancement, good first issue, frontend, crud, backend, api, architecture, breaking-change, devops, favicon

#132 Add comprehensive test suite for Languages controller
  .gitignore
  apps/api/drizzle/0000_reflective_wrecker.sql
  apps/api/drizzle/meta/0000_snapshot.json
  apps/api/drizzle/meta/_journal.json
  apps/api/package.json
  apps/api/src/controllers/language.controller.test.ts
  apps/api/src/controllers/languages.controller.test.ts
  apps/web/.env.example
  apps/web/app/dashboard/languages/page.tsx
  apps/web/components/dashboard/layout/sidebar/index.tsx
  turbo.json
Labels: enhancement, help wanted, good first issue, backend, high-priority, architecture

#135 Update congratulations workflow to use latest actions
  .github/workflows/congratulations.yml
Labels: documentation, architecture, devops

#141 Snowflake IDs and GameSeeder file.
  apps/api/docs/nodejs-snowflake.md
  apps/api/drizzle/0001_languages_trgm.sql
  apps/api/drizzle/meta/0000_snapshot.json
  apps/api/drizzle/meta/_journal.json
  apps/api/package.json
  apps/api/src/controllers/v1/games.controller.ts
  apps/api/src/db/schemas/games.drizzle.ts
  apps/api/src/db/seed/games.seeder.ts
  apps/api/src/utils/id-generator.ts
  apps/web/app/lfg/page.tsx
  apps/web/components/dashboard/lobby-list-item.tsx
  bun.lock
  package.json
  packages/shared/dto/game.dto.ts
Labels: backend, api, architecture

#142 🎨 feat(mobile): Enhanced UI with Modern Icons and Navigation
  apps/mobile/assets/Simulator Screenshot - iPhone 15 Pro - 2025-06-14 at 17.06.09.png
  apps/mobile/babel.config.js
  apps/mobile/components/mobile/BottomNavigation.tsx
  apps/mobile/components/mobile/MobileHeader.tsx
  apps/mobile/components/mobile/MobileHeroSection.tsx
  apps/mobile/components/mobile/PopularGames.tsx
  apps/mobile/components/mobile/QuickActions.tsx
  apps/mobile/metro.config.js
  apps/mobile/screens/HomeScreen.tsx
  apps/mobile/tsconfig.json
  bun.lock
  package.json
  tsconfig.json
  turbo.json
Labels: enhancement, good first issue, frontend

#162 Enhance API responses with success messages and structured data
  apps/api/src/controllers/v1/distributors.controller.ts
  apps/api/src/controllers/v1/event-attendees.controller.ts
  apps/api/src/controllers/v1/event-invitations.controller.ts
  apps/api/src/controllers/v1/game-modes.controller.ts
  apps/api/src/controllers/v1/game-ranks.controller.ts
  apps/api/src/controllers/v1/games.controller.ts
  apps/api/src/controllers/v1/languages.controller.ts
  apps/api/src/controllers/v1/lobbies.controller.ts
  apps/api/src/controllers/v1/platforms.controller.ts
  apps/api/src/controllers/v1/user-profiles.controller.ts
  apps/api/src/index.ts
  apps/api/src/locales/en-US.ts
  apps/api/src/locales/tr-TR.ts
  apps/web/app/dashboard/languages/page.tsx
  apps/web/components/platforms/platform-form.tsx
  apps/web/features/games/api/actions.ts
  apps/web/features/languages/api/actions.ts
  apps/web/features/platforms/api/actions.ts
  apps/web/utils/api-response-handler.ts
Labels: bug, documentation, enhancement, good first issue, crud, backend, api, architecture, infrastructure

#168 Refactor distributor, lobby, and platform controllers to use convertB…
  apps/api/src/controllers/v1/distributors.controller.ts
  apps/api/src/controllers/v1/lobbies.controller.ts
  apps/api/src/controllers/v1/platforms.controller.ts
Labels: backend

#185 Region and User Game Favorites.
  apps/api/src/db/schemas/user-favorite-games.drizzle.ts
  apps/api/src/db/schemas/user-profile.drizzle.ts
Labels: branding
